### ISSUE TITLE
The `$` is doubled when autocompleting variables

### ISSUE THREAD

**Issue by Taluu** [phpactor/ncm2-phpactor#1]
If I search a variable after typing as `$` (so `$` + `C-n`), for a `$foo` variable, I end up with a `$$foo` instead of expected `$foo`.

Not sure if it's phpactor or ncm, but I think it's form the plugin, as I didn't have the issue with deoplete.

**Comment by Taluu** [comment]
Hum, this doesn't appear to be fixed. I updated this morning the plugin, and I still have double `$`s.

Reproducing : Type `$`, and `<C-n>`. Variables are proposed. If we complete with one of those, we end up with `$$varName` if we selected `$varName.

**Comment by dantleech** [comment]
I can reproduce this issue on the previous commit, but after the fix it works as expected.

**Comment by Taluu** [comment]
Can't reproduce either... I was up to date, but maybe it's because I hadn't restarted nvim or something like that ?

**Comment by dantleech** [comment]
Yeah, that would probably do it :)
