### ISSUE TITLE
Default completion is ncm2

### ISSUE THREAD

**Issue by vivoconunxino** [phpactor/ncm2-phpactor#11]
I know this is more a missconfiguration than an issue, and I've been looking but I don't know how to fix it.
By default I'm getting what I think is the default ncm2 autocompletion (triggered automatically):
![ncm2completion](https://user-images.githubusercontent.com/6072490/46811124-6b011900-cd72-11e8-97d5-b3a69688a99d.png)
Then, if I press \<C-x\>\<C-o\> I get the phpactor source:
![ncm2completionphpactor](https://user-images.githubusercontent.com/6072490/46811160-810ed980-cd72-11e8-8b3c-03b5c49ab162.png)
How can I set up ncm2 in order to trigger automatically the phpactor suggestions instead of the default ones?

**Comment by roxma** [comment]
> How can I set up ncm2 in order to trigger automatically the phpactor suggestions instead of the default ones?

Remove this plugin.

Read the css example in ncm2 README. You might also need `:help ncm2#register_source`.

**Comment by dantleech** [comment]
From the screen short, this plugin _is_ returning the phpactor suggestions. The omni-complete suggestions are the same?

**Comment by vivoconunxino** [comment]
> From the screen shot, this plugin _is_ returning the phpactor suggestions. The omni-complete suggestions are the same? ncm2 does not, by default, complete PHP.

The first image is what I think omni-complete, second (pressing \<C-x\>\<C-o\>) phpactor. The look different despite both are perfectly valid

**Comment by dantleech** [comment]
Yep that's expected. One is using native VIM omni-complete, the other ncm2

**Comment by vivoconunxino** [comment]
> > How can I set up ncm2 in order to trigger automatically the phpactor suggestions instead of the default ones?
> 
> Remove this plugin.
> 
> Read the css example in ncm2 README. You might also need `:help ncm2#register_source`.

I removed 'phpactor/ncm2-phpactor', then in my vimrc:
autocmd FileType php setlocal omnifunc=phpactor#Complete
```
au User Ncm2Plugin call ncm2#register_source({
            \ 'name' : 'php',
            \ 'priority': 9, 
            \ 'subscope_enable': 1,
            \ 'scope': ['php'],
            \ 'mark': 'php',
            \ 'word_pattern': '[\w\-]+',
            \ 'complete_pattern': ['->'],
            \ 'on_complete': ['phpactor#Complete'],
            \ })

And after "$this->" I can see that automatically it's being called, but there is some kind of error:
`[ncm2_core@yarp]  php on_complete: Vim(call):E119: Not enough arguments for function: phpactor#Complete`
```

**Comment by dantleech** [comment]
Just out of interest, why would you do this? :)

**Comment by vivoconunxino** [comment]
With "your plugin" I mean Phpactor of course.

**Comment by roxma** [comment]
It is important to keep the 'ncm2#on_complete#omni' in the on_complete field.

**Comment by vivoconunxino** [comment]
> Yep that's expected. One is using native VIM omni-complete, the other ncm2 (both are using Phactor underneath)

Ok, got it; Both are using phpactor but they represent the list in different ways. Thanks
