### ISSUE TITLE
Open preview window on auto completing

### ISSUE THREAD

**Issue by Charliiee** [phpactor/ncm2-phpactor#19]
Currently, NCM2 doesn't seem to provide detailed info about functions being completed which, in result, does not display the preview window (or the brand new **floating window** as of neovim 4.0). 

There are cases though where opening the preview window would be great, e.g. when you have a method suggestion with tons of default arguments, which don't get auto-completed.

Obs: _It would also be really nice to have ncm2 providing a basic description to the suggested methods/functions (like their phpDoc comment if any i.e)_

**Comment by dantleech** [comment]
Maybe @roxma can say if floating / preview support would be possible in NCM2 ?

Phpactor currently provides this information through the [hover](https://phpactor.github.io/phpactor/vim-plugin.html#keyboard-mappings) shortcut - which I guess should eventually be displayed in a floating window (and include the docblock info, as currently it's just the method synposis).

**Comment by roxma** [comment]
You could try this plugin: https://github.com/ncm2/float-preview.nvim

**Comment by dantleech** [comment]
I guess this can be closed now that #20 was closed.
