### ISSUE TITLE
Composer and git only found when opening a file directly

### ISSUE THREAD

**Issue by JasonMiesionczek** [phpactor/ncm2-phpactor#25]
I can get ncm2-phpactor to work only when I open a file directly from the command line, e.g.: nvim ~/Projects/<project>/src/Controller/SomeController.php

If i open nvim in ~/Project/<project> and use NERDTree to open a file, composer and git are not found and completion does not function as expected. 

Is there something I can do to fix this? Thanks,

**Comment by dantleech** [comment]
A current precondition to a functioning Phpactor is that VIM is strated in the project root (the directory that has the `composer.json` file.

After starting VIM what does `:call phpactor#Status()` show?

**Comment by JasonMiesionczek** [comment]
When i start nvim in the project root directory, i get this:
`E117: Unknown function: phpactor#Status`
once i open a file via NERDTree i get this:
`Info                                                                                    
----
Version: 632d0bb (6 months ago) 0.12.0-746
Work dir: /home/jason/Projects/<project>/src/Controller

Diagnostics
-----------
[✔] XDebug is disabled. XDebug has a negative effect on performance.
[✘] Composer not found - some functionality will not be available (e.g. class creation) and class
location will fallback to scanning the filesystem - this can be slow. Make sure you've run `compos
er install` in your project!
[✘] Git not detected. Some operations which would have been better scoped to your project reposito
ry will now include vendor paths.
Config files
------------
[✘] /home/jason/.config/phpactor/phpactor.json
[✘] /home/jason/.config/phpactor/phpactor.yml
[✘] /home/jason/Projects/<project>/src/Controller/.phpactor.json
[✘] /home/jason/Projects/<project>/src/Controller/.phpactor.yml`

**Comment by JasonMiesionczek** [comment]
nevermind, i figured it out, i had `autochdir` set in my config, removing that fixed it.
